const reduxTypes = {
  Auth: {
    SIGN_IN_FETCH: 'SIGN_IN_FETCH',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    RESET_DATA: 'RESET_DATA',
    KEEP_SIGN_IN: 'KEEP_SIGN_IN',
    USER_UPDATE_PROFILE: 'USER_UPDATE_PROFILE',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    COGNITO_POOL_DATA: 'COGNITO_POOL_DATA',
    SESSION_ACTIVE: 'SESSION_ACTIVE',
    SESSION_INACTIVE: 'SESSION_INACTIVE',

    UPDATE_SIGN_IN: 'UPDATE_SIGN_IN',
    ADD_RESET_PASSWORD_TOKEN: 'ADD_RESET_PASSWORD_TOKEN',
    REMOVE_RESET_PASSWORD_TOKEN: 'REMOVE_RESET_PASSWORD_TOKEN',

    //Check
    CHECK_FETCH: 'CHECK_FETCH',
    CHECK_SUCCESS: 'CHECK_SUCCESS',
    CHECK_FAILURE: 'CHECK_FAILURE',

    // OIDC
    SET_USER: 'SET_USER',
    SET_USER_MANAGER: 'SET_USER_MANAGER',
    USER_EXPIRED: 'USER_EXPIRED',
    SILENT_RENEW_ERROR: 'SILENT_RENEW_ERROR',
    SESSION_TERMINATED: 'SESSION_TERMINATED',
    USER_EXPIRING: 'USER_EXPIRING',
    USER_FOUND: 'USER_FOUND',
    USER_SIGNED_OUT: 'USER_SIGNED_OUT',
    LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  },
  Loading: {
    UPDATE_LOADING: 'UPDATE_LOADING',
    LOADING_VISIBLE: 'LOADING_VISIBLE',
    LOADING_HIDE: 'LOADING_HIDE',
    LOADING: 'LOADING',
  },
  SignUp: {
    ADD_EMAIL: 'ADD_EMAIL',
    ADD_DOMAIN: 'ADD_DOMAIN',
    CLEAR_SIGN_UP_DATA: 'CLEAR_SIGN_UP_DATA',
    UPDATE_SIGNUP_INFO: 'UPDATE_SIGNUP_INFO',
  },
  Post: {
    POST_DATA_CLEAR: 'POST_DATA_CLEAR',
    POST_CREATE_FETCH: 'POST_CREATE_FETCH',
    POST_CREATE_SUCCESS: 'POST_CREATE_SUCCESS',
    POST_CREATE_ERROR: 'POST_CREATE_ERROR',
    POST_UPDATE_FETCH: 'POST_UPDATE_FETCH',
    POST_UPDATE_SUCCESS: 'POST_UPDATE_SUCCESS',
    POST_UPDATE_ERROR: 'POST_UPDATE_ERROR',
    POST_DELETE_SUCCESS: 'POST_DELETE_SUCCESS',
    POST_UPDATE_LOCAL: 'POST_UPDATE_LOCAL',
  },
  Feed: {
    POST_LIST_FETCH: 'POST_LIST_FETCH',
    POST_UPDATE_LIST_SUCCESS: 'POST_UPDATE_LIST_SUCCESS',
    POST_UPDATE_LIST_ERROR: 'POST_UPDATE_LIST_ERROR',
    FEED_UPDATE_CATEGORIES_SELECTED: 'FEED_UPDATE_CATEGORIES_SELECTED',
    POST_UPDATE_LIST_INITIATIVES: 'POST_UPDATE_LIST_INITIATIVES',
    POST_UPDATE_LIST_SEARCH: 'POST_UPDATE_LIST_SEARCH',
    USER_UPDATE_LIST_SEARCH: 'USER_UPDATE_LIST_SEARCH'
  },
  Comment: {
    COMMENTS_GET_LIST_FETCH: 'COMMENTS_GET_LIST_FETCH',
    COMMENTS_GET_LIST_SUCCESS: 'COMMENTS_GET_LIST_SUCCESS',
    COMMENTS_GET_LIST_ERROR: 'COMMENTS_GET_LIST_ERROR',

    COMMENTS_CLEAR: 'COMMENTS_CLEAR',

    COMMENT_ADD_NEW: 'COMMENT_ADD_NEW',
    COMMENT_SEND_SUCCESS: 'COMMENTS_GET_LIST_SUCCESS',
  },
};

export default reduxTypes;
